version: '3.7'
services:
  cleanrepo-backend:
    image: cleanrepo-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cleanrepo-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/codepred?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
    volumes:
      - ./files:/var/cleanrepo-files
    networks:
      - cleanrepo-net
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "3309:5432"
    volumes:
      - cleanrepo-postgres-data:/var/lib/postgresql/data
    networks:
      - cleanrepo-net
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

volumes:
  cleanrepo-postgres-data:

networks:
  cleanrepo-net:
    name: cleanrepo-net

